keycloak:
  server-url: http://localhost:9090
  realm: istad
  client-id: postman
  client-secret: aMkzTqFZN6KCIMStRIlzO2JAvi98PYXr
  grant-type: client_credentials

file-upload:
  client-path: /file
  server-path: D:\Bchelor\backend\upload\
  base-uri: http://localhost:${server.port}${file-upload.client-path}


server:
  port: 9999

spring:
  jpa:
    hibernate:
      ddl-auto: update # create, drop, alter, truncate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9432/db_commerce
    username: ${DB_USERNAME:e1usr}
    password: ${DB_PASSWORD:qwerqwer}
  application:
    name: ecommerce-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/istad

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


