spring:
  jpa:
    hibernate:
      ddl-auto: update # create, drop, alter, truncate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4444/ec_db
    username: ${DB_USERNAME:ec}
    password: ${DB_PASSWORD:qwer}
  application:
    name: ecommerce-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/istad

kind: Application
server:
  port: 9999
