spring:
  jpa:
    hibernate:
      ddl-auto: update # create, drop, alter, truncate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4444/ec_db
    username: ${DB_USERNAME:ec}
    password: ${DB_PASSWORD:qwer}
  application:
    name: ecommerce-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/istad

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file-upload:
  client-path: /file
  server-path: D:\Bchelor\backend\upload\
  base-uri: http://localhost:${server.port}${file-upload.client-path}


kind: Application
server:
  port: 9999
