networks:
  e1-net:
    external: true
volumes:
  ecommerce-db-e1-vol:
services:
  ecommerce-db-e1:
    image: postgres:18.4
    container_name: ecommerce-db-e1
    ports:
      - "9432:5432"
    environment:
      POSTGRES_PASSWORD: qwerqwer
      POSTGRES_USER: e1usr
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - ecommerce-db-e1-vol:/var/lib/postgresql/18/docker
    networks:
      - e1-net
